#!/usr/bin/env python3
"""
Compare Template Search TM-scores vs Proteina Sampling TM-scores

This script creates scatter plots comparing TM-scores obtained from:
1. Template search protocol (hhsearch + structure alignment)
2. Proteina generative sampling protocol (both predicted and reference templates)

Note: Results assume template search was run with k=5 to match Proteina's top-5 sampling.

Two scorer modes are supported:
  - AF2Rank mode: the cross-protein summary CSV contains top_1_tm_ref_pred / top_5_tm_ref_pred
    (generated by the old full-AF2Rank pipeline).
  - ProteinEBM mode: the cross-protein summary CSV was generated with --scorer proteinebm and
    does NOT contain tm_ref_pred columns.  In this case --af2rank_topk_csv must point to the
    af2rank_on_proteinebm_topk cross-protein summary (produced with --af2rank_top_k > 0), which
    contains top_1_tm_ref_pred / top_5_tm_ref_pred for the top-k ProteinEBM-selected templates.

Subset filtering:
  - When --list_csv is omitted, every protein in --proteina_results_csv is processed.
  - When --list_csv is provided, results are filtered to IDs in that CSV (column controlled
    by --list_id_column, default "pdb").

Labelling:
  - --label "Monomers" appends " (Monomers)" to figure titles and "_monomer" to output
    filenames. Default empty = no suffix.

Usage examples:
  # Plain run (no subset filter, AF2Rank pipeline):
  python compare_template_vs_proteina.py \\
    --proteina_results_csv ~/proteina/inference/<run>/bad_afdb_cross_protein_analysis/cross_protein_summary_data.csv \\
    --output_dir ~/data/bad_afdb/comparison_template_vs_proteina

  # Monomer subset:
  python compare_template_vs_proteina.py \\
    --proteina_results_csv ~/proteina/inference/<run>/bad_afdb_cross_protein_analysis/cross_protein_summary_data.csv \\
    --list_csv ~/data/bad_afdb/pdb_70_cluster_reps_aligned_confidence_aggregate_monomer_length_50-640_tm-05.csv \\
    --label "Monomers" \\
    --output_dir ~/data/bad_afdb/comparison_template_vs_proteina_monomer

  # ProteinEBM pipeline (new):
  python compare_template_vs_proteina.py \\
    --proteina_results_csv ~/proteina/inference/<run>/bad_afdb_cross_protein_analysis/cross_protein_summary_data.csv \\
    --af2rank_topk_csv    ~/proteina/inference/<run>/bad_afdb_cross_protein_analysis/cross_protein_summary_data_topk.csv \\
    --output_dir ~/data/bad_afdb/comparison_template_vs_proteina
"""

import argparse
import re
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from scipy import stats

# Default paths (only --template_aln_dir has a usable default; the rest are CLI required).
DEFAULT_TEMPLATE_ALN_DIR = Path(Path.home() / "data/bad_afdb/template_aln")


def _slugify(label: str) -> str:
    """Lowercase, collapse non-alphanumerics to '_', strip leading/trailing '_'."""
    slug = re.sub(r'[^a-zA-Z0-9]+', '_', label).strip('_').lower()
    return slug


def parse_usalign_tsv(tsv_file):
    """Parse USalign output TSV file to extract TM1 scores."""
    tm_scores = []

    with open(tsv_file, 'r') as f:
        for line in f:
            if line.startswith('#'):
                continue
            line = line.strip()
            if not line or line.startswith('Warning'):
                continue
            parts = line.split('\t')
            if len(parts) >= 3:
                # Column 2 (index 2) is TM1
                tm1 = float(parts[2])
                tm_scores.append(tm1)

    return tm_scores


def load_template_search_results(all_protein_ids, template_aln_dir: Path):
    """
    Load template search results by parsing individual alignment files.
    For proteins without results (failed searches), set TM-scores to 0.0.
    """
    results = []

    # Get all .tsv files in template_aln directory
    tsv_files = {f.stem: f for f in template_aln_dir.glob("*.tsv")
                 if f.name != "tm_scores_results.tsv"}

    for protein_id in all_protein_ids:
        if protein_id in tsv_files:
            # Parse TM scores
            tm_scores = parse_usalign_tsv(tsv_files[protein_id])

            if tm_scores:
                results.append({
                    'protein_id': protein_id,
                    'template_top_1': tm_scores[0],  # First score (top-1 by sum_probs)
                    'template_top_5': max(tm_scores),  # Maximum score among all
                    'template_failed': False
                })
            else:
                # Empty file
                results.append({
                    'protein_id': protein_id,
                    'template_top_1': 0.0,
                    'template_top_5': 0.0,
                    'template_failed': True
                })
        else:
            # No result file (MSA search failed)
            results.append({
                'protein_id': protein_id,
                'template_top_1': 0.0,
                'template_top_5': 0.0,
                'template_failed': True
            })

    return pd.DataFrame(results)


def detect_scorer_mode(proteina_df: pd.DataFrame) -> str:
    """
    Detect whether the cross-protein summary was generated by AF2Rank or ProteinEBM.
    Returns 'af2rank' or 'proteinebm'.
    """
    if 'top_1_tm_ref_pred' in proteina_df.columns and 'top_5_tm_ref_pred' in proteina_df.columns:
        return 'af2rank'
    return 'proteinebm'


def load_and_merge_data(
    proteina_results_csv: Path,
    template_aln_dir: Path,
    af2rank_topk_csv: Path | None,
    list_csv: Path | None,
    list_id_column: str,
):
    """Load datasets, optionally filter by a list CSV, and merge on protein ID."""
    # Load Proteina results
    proteina_df = pd.read_csv(proteina_results_csv)

    # Detect scorer mode
    scorer_mode = detect_scorer_mode(proteina_df)
    print(f"Detected scorer mode: {scorer_mode.upper()}")

    if scorer_mode == 'proteinebm':
        if af2rank_topk_csv is None:
            print(
                "\nERROR: ProteinEBM scorer mode detected — the cross-protein summary does not contain\n"
                "  top_1_tm_ref_pred / top_5_tm_ref_pred (AF2 prediction quality columns).\n"
                "  These are only produced by the AF2Rank-on-ProteinEBM-top-k step.\n"
                "  Please re-run the pipeline with --af2rank_top_k > 0 and then supply the\n"
                "  resulting cross-protein summary via --af2rank_topk_csv.",
                file=sys.stderr,
            )
            sys.exit(1)

        topk_df = pd.read_csv(af2rank_topk_csv)
        missing_pred = [c for c in ('top_1_tm_ref_pred', 'top_5_tm_ref_pred') if c not in topk_df.columns]
        if missing_pred:
            print(
                f"\nERROR: --af2rank_topk_csv is missing required columns: {missing_pred}\n"
                f"  Found columns: {topk_df.columns.tolist()}\n"
                f"  Ensure the file was generated by generate_cross_protein_plots.py with\n"
                f"  --scorer af2rank_on_proteinebm_topk --af2rank_top_k > 0.",
                file=sys.stderr,
            )
            sys.exit(1)

        # Merge the AF2 prediction columns into the main ProteinEBM summary.
        # top_1/5_tm_ref_template come from the main ProteinEBM summary (all templates);
        # top_1/5_tm_ref_pred come from the af2rank_topk summary (top-k templates only).
        pred_cols = ['protein_id', 'top_1_tm_ref_pred', 'top_5_tm_ref_pred']
        proteina_df = proteina_df.merge(
            topk_df[[c for c in pred_cols if c in topk_df.columns]],
            on='protein_id',
            how='left',
        )
        print(f"Merged AF2Rank top-k pred columns from: {af2rank_topk_csv}")

    # Optional subset filter
    if list_csv is not None:
        list_df = pd.read_csv(list_csv)
        if list_id_column not in list_df.columns:
            print(
                f"\nERROR: --list_csv {list_csv} has no column '{list_id_column}'.\n"
                f"  Found columns: {list_df.columns.tolist()}\n"
                f"  Pass the correct column via --list_id_column.",
                file=sys.stderr,
            )
            sys.exit(1)
        subset_ids = set(list_df[list_id_column].values)
        print(f"Subset protein IDs from --list_csv ({list_id_column}): {len(subset_ids)}")
        proteina_df = proteina_df[proteina_df['protein_id'].isin(subset_ids)]
        print(f"Proteina results after subset filter: {len(proteina_df)}")
    else:
        print("No --list_csv provided — processing all proteins in --proteina_results_csv.")

    # Get all protein IDs from (filtered) Proteina data
    all_protein_ids = proteina_df['protein_id'].values

    # Load template search results (including failed ones with TM=0)
    template_df = load_template_search_results(all_protein_ids, template_aln_dir)

    # Merge on protein_id
    merged_df = pd.merge(
        template_df,
        proteina_df,
        on='protein_id',
        how='inner',
    )

    print(f"Template search results: {len(template_df)} proteins")
    print(f"  - Successful: {(~template_df['template_failed']).sum()}")
    print(f"  - Failed (TM=0): {template_df['template_failed'].sum()}")
    print(f"Merged dataset: {len(merged_df)} proteins")

    return merged_df


def create_scatter_plot(x, y, xlabel, ylabel, title, output_file, add_stats=True, filter_threshold=None):
    """Create a scatter plot with x=y diagonal line and statistics."""
    fig, ax = plt.subplots(figsize=(8, 8))

    # Apply filter if specified
    if filter_threshold is not None:
        mask = (x >= filter_threshold) | (y >= filter_threshold)
        x_plot = x[mask]
        y_plot = y[mask]
        title = f"{title}\n(Filtered: at least one value ≥ {filter_threshold})"
    else:
        x_plot = x
        y_plot = y

    # Scatter plot
    ax.scatter(x_plot, y_plot, alpha=0.6, s=50, edgecolors='black', linewidth=0.5)

    # Diagonal line (x=y)
    min_val = 0
    max_val = 1
    ax.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='x=y', alpha=0.7)

    if add_stats and len(x_plot) > 0:
        # Calculate statistics
        pearson_r, pearson_p = stats.pearsonr(x_plot, y_plot)
        spearman_r, spearman_p = stats.spearmanr(x_plot, y_plot)

        # # Paired t-test (two-sided)
        # t_stat, t_p = stats.ttest_rel(y_plot, x_plot)

        # # Wilcoxon signed-rank test (two-sided)
        # wilcoxon_stat, wilcoxon_p = stats.wilcoxon(y_plot, x_plot, alternative='two-sided')

        # Add correlation statistics text
        stats_text = f'Pearson r = {pearson_r:.3f} (p={pearson_p:.2e})\n'
        stats_text += f'Spearman ρ = {spearman_r:.3f} (p={spearman_p:.2e})'
        ax.text(0.05, 0.95, stats_text, transform=ax.transAxes,
                verticalalignment='top', bbox=dict(boxstyle='round', facecolor='white', alpha=0.8),
                fontsize=10)

        # # Add difference statistics
        # mean_diff = (y_plot - x_plot).mean()
        # diff_text = f'Mean Δ = {mean_diff:.4f}\n'
        # diff_text += f'Paired t-test: p={t_p:.2e}\n'
        # diff_text += f'Wilcoxon: p={wilcoxon_p:.2e}\n'
        # diff_text += f'N = {len(x_plot)}'
        # ax.text(0.05, 0.05, diff_text,
        #         transform=ax.transAxes, verticalalignment='bottom',
        #         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8), fontsize=10)

    ax.set_xlabel(xlabel, fontsize=12)
    ax.set_ylabel(ylabel, fontsize=12)
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.legend(loc='lower right')
    ax.grid(True, alpha=0.3)
    ax.set_aspect('equal', adjustable='box')

    # Set limits to [0, 1]
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_file}")
    plt.close()

    if add_stats and len(x_plot) > 0:
        return {
            'pearson_r': pearson_r,
            'spearman_r': spearman_r,
            # 't_stat': t_stat,
            # 't_p': t_p,
            # 'wilcoxon_stat': wilcoxon_stat,
            # 'wilcoxon_p': wilcoxon_p,
            # 'mean_diff': mean_diff,
            'n_samples': len(x_plot)
        }
    return None


def print_significance_results(comparison_name, results, alpha=0.05):
    """Print statistical significance results."""
    print(f"\n{comparison_name} (N={results['n_samples']}):")
    print(f"  Pearson correlation:  r={results['pearson_r']:.4f}")
    print(f"  Spearman correlation: ρ={results['spearman_r']:.4f}")
    # print(f"  Mean difference (Proteina - Template): {results['mean_diff']:.4f}")
    # print(f"  Paired t-test: t={results['t_stat']:.4f}, p={results['t_p']:.2e}", end='')
    # if results['t_p'] < alpha:
    #     print(f" ***SIGNIFICANT*** (α={alpha})")
    # else:
    #     print(f" (not significant at α={alpha})")
    # print(f"  Wilcoxon signed-rank: stat={results['wilcoxon_stat']:.1f}, p={results['wilcoxon_p']:.2e}", end='')
    # if results['wilcoxon_p'] < alpha:
    #     print(f" ***SIGNIFICANT*** (α={alpha})")
    # else:
    #     print(f" (not significant at α={alpha})")

    # # Interpretation
    # if results['t_p'] < alpha or results['wilcoxon_p'] < alpha:
    #     if results['mean_diff'] > 0:
    #         print(f"  → Proteina is SIGNIFICANTLY BETTER than template search")
    #     else:
    #         print(f"  → Template search is SIGNIFICANTLY BETTER than Proteina")
    # else:
    #     print(f"  → No significant difference between methods")


# Base comparison spec (label suffix is applied at run time)
BASE_COMPARISONS = [
    # Template vs Proteina Predicted
    {
        'x_col': 'template_top_1',
        'y_col': 'top_1_tm_ref_pred',
        'x_label': 'Template Search Top-1 TM-score',
        'y_label': 'Proteina Predicted Top-1 TM-score',
        'base_title': 'Top-1: Template vs Proteina Predicted',
        'base_output': 'comparison_top_1_template_vs_proteina_pred',
    },
    {
        'x_col': 'template_top_5',
        'y_col': 'top_5_tm_ref_pred',
        'x_label': 'Template Search Top-5 TM-score',
        'y_label': 'Proteina Predicted Top-5 TM-score',
        'base_title': 'Top-5: Template vs Proteina Predicted',
        'base_output': 'comparison_top_5_template_vs_proteina_pred',
    },
    # Template vs Proteina Reference Template
    {
        'x_col': 'template_top_1',
        'y_col': 'top_1_tm_ref_template',
        'x_label': 'Template Search Top-1 TM-score',
        'y_label': 'Proteina Reference Template Top-1 TM-score',
        'base_title': 'Top-1: Template vs Proteina Ref Template',
        'base_output': 'comparison_top_1_template_vs_proteina_ref_template',
    },
    {
        'x_col': 'template_top_5',
        'y_col': 'top_5_tm_ref_template',
        'x_label': 'Template Search Top-5 TM-score',
        'y_label': 'Proteina Reference Template Top-5 TM-score',
        'base_title': 'Top-5: Template vs Proteina Ref Template',
        'base_output': 'comparison_top_5_template_vs_proteina_ref_template',
    },
]


def build_comparisons(label: str):
    """Apply --label to title/filename of each base comparison."""
    title_suffix = f" ({label})" if label else ""
    name_suffix = f"_{_slugify(label)}" if label else ""
    comparisons = []
    for c in BASE_COMPARISONS:
        comparisons.append({
            'x_col': c['x_col'],
            'y_col': c['y_col'],
            'x_label': c['x_label'],
            'y_label': c['y_label'],
            'title': c['base_title'] + title_suffix,
            'output_base': c['base_output'] + name_suffix,
        })
    return comparisons


def main():
    """Main analysis function."""
    parser = argparse.ArgumentParser(
        description="Compare template search TM-scores vs Proteina sampling TM-scores"
    )
    parser.add_argument(
        '--proteina_results_csv', required=True,
        help='Path to the cross-protein summary CSV produced by generate_cross_protein_plots.py '
             '(e.g. .../bad_afdb_cross_protein_analysis/cross_protein_summary_data.csv)',
    )
    parser.add_argument(
        '--af2rank_topk_csv', default=None,
        help='Path to the af2rank_on_proteinebm_topk cross-protein summary CSV '
             '(required when --scorer=proteinebm was used in the pipeline, i.e. when '
             'top_1_tm_ref_pred is absent from --proteina_results_csv).',
    )
    parser.add_argument(
        '--list_csv', default=None,
        help='Optional CSV with the subset of protein IDs to process. When omitted, all '
             'proteins in --proteina_results_csv are processed.',
    )
    parser.add_argument(
        '--list_id_column', default='pdb',
        help='Column in --list_csv that contains protein IDs matching the "protein_id" '
             'column of the cross-protein summary (default: "pdb").',
    )
    parser.add_argument(
        '--template_aln_dir', default=str(DEFAULT_TEMPLATE_ALN_DIR),
        help=f'Directory of per-protein USalign .tsv files '
             f'(default: {DEFAULT_TEMPLATE_ALN_DIR}).',
    )
    parser.add_argument(
        '--output_dir', required=True,
        help='Output directory for plots.',
    )
    parser.add_argument(
        '--label', default='',
        help='Optional label appended to figure titles (as " (<label>)") and output '
             'filenames (as "_<slugified-label>"). Empty = no suffix.',
    )
    args = parser.parse_args()

    proteina_results_csv = Path(args.proteina_results_csv).expanduser()
    af2rank_topk_csv = Path(args.af2rank_topk_csv).expanduser() if args.af2rank_topk_csv else None
    list_csv = Path(args.list_csv).expanduser() if args.list_csv else None
    template_aln_dir = Path(args.template_aln_dir).expanduser()
    output_dir = Path(args.output_dir).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)
    label = args.label

    print("=" * 80)
    print("Comparing Template Search (k=5) vs Proteina Sampling TM-scores")
    if label:
        print(f"Label: {label}")
    print("=" * 80)
    print(f"Proteina results CSV : {proteina_results_csv}")
    if af2rank_topk_csv:
        print(f"AF2Rank top-k CSV    : {af2rank_topk_csv}")
    if list_csv:
        print(f"List CSV             : {list_csv} (id column: {args.list_id_column})")
    print(f"Template aln dir     : {template_aln_dir}")
    print(f"Output directory     : {output_dir}")
    print()

    # Load data
    df = load_and_merge_data(
        proteina_results_csv=proteina_results_csv,
        template_aln_dir=template_aln_dir,
        af2rank_topk_csv=af2rank_topk_csv,
        list_csv=list_csv,
        list_id_column=args.list_id_column,
    )

    if len(df) == 0:
        print("ERROR: No matching proteins found between datasets!")
        return

    comparisons = build_comparisons(label)

    print("\n" + "=" * 80)
    print("Creating comparison plots...")
    print("=" * 80)

    all_results = {}

    for idx, comp in enumerate(comparisons, 1):
        print(f"\n{idx}. {comp['title']}")

        # Full dataset
        results_full = create_scatter_plot(
            x=df[comp['x_col']],
            y=df[comp['y_col']],
            xlabel=comp['x_label'],
            ylabel=comp['y_label'],
            title=comp['title'],
            output_file=output_dir / f"{comp['output_base']}.png",
        )
        all_results[f"{comp['output_base']}_full"] = results_full

        # Filtered dataset (at least one value >= 0.5)
        results_filtered = create_scatter_plot(
            x=df[comp['x_col']],
            y=df[comp['y_col']],
            xlabel=comp['x_label'],
            ylabel=comp['y_label'],
            title=comp['title'],
            output_file=output_dir / f"{comp['output_base']}_filtered_0.5.png",
            filter_threshold=0.5,
        )
        all_results[f"{comp['output_base']}_filtered"] = results_filtered

    # Summary statistics
    label_tag = f" [{label}]" if label else ""

    print("\n" + "=" * 80)
    print(f"STATISTICAL ANALYSIS - FULL DATASETS{label_tag}")
    print("=" * 80)

    for comp in comparisons:
        key = f"{comp['output_base']}_full"
        if key in all_results and all_results[key]:
            print_significance_results(comp['title'], all_results[key])

    print("\n" + "=" * 80)
    print(f"STATISTICAL ANALYSIS - FILTERED DATASETS (≥0.5){label_tag}")
    print("=" * 80)

    for comp in comparisons:
        key = f"{comp['output_base']}_filtered"
        if key in all_results and all_results[key]:
            print_significance_results(f"{comp['title']} [Filtered]", all_results[key])

    # Additional analysis: Which method performs better?
    print("\n" + "=" * 80)
    print(f"METHOD COMPARISON SUMMARY - FULL DATASET{label_tag}")
    print("=" * 80)

    # Compare Template vs Proteina Predicted
    for k in [1, 5]:
        template_col = f'template_top_{k}'
        proteina_col = f'top_{k}_tm_ref_pred'

        better_proteina = (df[proteina_col] > df[template_col]).sum()
        better_template = (df[template_col] > df[proteina_col]).sum()
        equal = (df[template_col] == df[proteina_col]).sum()

        print(f"\nTop-{k} (Template vs Proteina Predicted):")
        print(f"  Proteina better: {better_proteina} ({100*better_proteina/len(df):.1f}%)")
        print(f"  Template better: {better_template} ({100*better_template/len(df):.1f}%)")
        print(f"  Equal: {equal}")
        print(f"  Mean Template: {df[template_col].mean():.4f} ± {df[template_col].std():.4f}")
        print(f"  Mean Proteina: {df[proteina_col].mean():.4f} ± {df[proteina_col].std():.4f}")
        print(f"  Median Template: {df[template_col].median():.4f}")
        print(f"  Median Proteina: {df[proteina_col].median():.4f}")

    # Compare Template vs Proteina Reference Template
    for k in [1, 5]:
        template_col = f'template_top_{k}'
        proteina_col = f'top_{k}_tm_ref_template'

        better_proteina = (df[proteina_col] > df[template_col]).sum()
        better_template = (df[template_col] > df[proteina_col]).sum()
        equal = (df[template_col] == df[proteina_col]).sum()

        print(f"\nTop-{k} (Template vs Proteina Ref Template):")
        print(f"  Proteina better: {better_proteina} ({100*better_proteina/len(df):.1f}%)")
        print(f"  Template better: {better_template} ({100*better_template/len(df):.1f}%)")
        print(f"  Equal: {equal}")
        print(f"  Mean Template: {df[template_col].mean():.4f} ± {df[template_col].std():.4f}")
        print(f"  Mean Proteina: {df[proteina_col].mean():.4f} ± {df[proteina_col].std():.4f}")
        print(f"  Median Template: {df[template_col].median():.4f}")
        print(f"  Median Proteina: {df[proteina_col].median():.4f}")

    print("\n" + "=" * 80)
    print("Analysis complete!")
    print("=" * 80)


if __name__ == "__main__":
    main()
