data_dir: ${oc.env:DATA_PATH}/pdb_cath/
cath_code_file: cath_code_list.csv

# Model checkpoint paths
ckpt_path: /path/to/cirpin/trained/model.ckpt  # Path to the CIRPIN-trained model checkpoint

# Generation parameters
dt: 0.005
nsamples_per_len: 10
max_nsamples: 10

# Conditioning options
fold_cond: True   # Can be used together with CIRPIN
cirpin_cond: True # Enable CIRPIN conditioning
seq_cond: True

# CIRPIN conditioning parameters (must match training config)
cirpin:
  emb_path: "/path/to/cirpin/embeddings.pt"  # Path to CIRPIN embeddings .pt file
  emb_dim: 256  # Must match the dimension used during training

# Sampling parameters
sampling_mode: sc  # Options are: vf (plain flow matching) or sc (using score)
sc_scale_noise: 0.4  # scale used to multiply noise if mode == sc
sc_scale_score: 1.0  # scale used to multiply score if mode == sc
gt_mode: "1/t"  # us, tan, or 1/t
gt_p: 1.0  # float
gt_clamp_val: null  # 10.0 float or null

# Output settings
output_dir: "./cirpin_generated_proteins/"
save_format: "pdb"  # pdb or pt

# Model architecture (must match training)
defaults:
  - model: caflow
  - override model/nn: ca_af3_400M_cirpin
  - _self_ 